app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app_api:
    path: /api/
    methods: GET
    controller: App\Controller\ApiController::index

app_api_recuperar_tablero:
    path: /api/recuperar_tablero
    methods: GET
    controller: App\Controller\ApiController::recuperarTablero

app_api_crear_tablero:
    path: /api/crear_tablero
    methods: POST
    controller: App\Controller\ApiController::crearTablero

app_api_modificar_tablero:
    path: /api/modificar_tablero
    methods: PUT
    controller: App\Controller\ApiController::modificarTablero

app_api_grabar_tablero:
    path: /api/grabar_tablero/{id}
    methods: PUT
    controller: App\Controller\ApiController::grabarTablero