app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }

app_api:
    path: /api/
    methods: GET
    controller: App\Controller\ApiController::index

app_api_crear_tablero:
    path: /api/crear_tablero
    methods: POST
    controller: App\Controller\ApiController::crearTablero

app_api_borrar_tablero:
    path: /api/borrar_tablero
    methods: DELETE
    controller: App\Controller\ApiController::borrarTablero

app_api_modificar_tablero:
    path: /api/modificar_tablero
    methods: PUT
    controller: App\Controller\ApiController::modificarTablero